api:
  dashboard: true

log:
  level: INFO
  # filepath: /var/log/traefik.log

accesslog:
  # filepath: /var/log/traefik-access.log

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  swarm:
    exposedByDefault: false
    network: proxy

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certResolver: letencrypt

certificatesResolvers:
  letencrypt:
    acme:
      email: me@briangebel.com
      storage: /certs/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

# Uncomment and configure if needed:
#  cloudflare:
#    acme:
#      <cloudflare options>